# This is a basic workflow to help you get started with Actions

name: CI with Java and gradle

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #Setup Java
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Checkout our code
        uses: actions/checkout@v2

      # Make gradle executable
      - name: Make gradle executable
        run: chmod +x ./gradlew

      # Run our build usig Gradle
      - name: Build with gradle
        run: ./gradlew build 

      #Create Build scan
      - name: Do build scan
        run: ./gradlew build  --scan
